### ISSUE TITLE
Isolate flush as small service.

### ISSUE THREAD

**Issue by fesor** [Arky9782/chat#5]
https://github.com/Arky9782/chat/blob/45a9451f3a13ff704858bd9afc52ce0ecad4076d/src/AppBundle/Controller/DefaultController.php#L59

`EntityManager` has fat interface. Try to not rely on it and wrap portion of needed functionality in your specialized interface. For example you could add service:

```
final class Flush
{
    // todo
    public function __invoke() {
        $this->em->flush();
    }
}
```

and use it in controller as:

```php
public function someAction(Flush $flush) {
    // do stuff
    $flush();
    // send response.
}
```

**Comment by ostretsov** [comment]
What would you recommend in case you need to do some merge logic with `$em->remove()`. Isolate it in kind of `*Repository`, add `final class Remove` service or something else?

**Comment by fesor** [comment]
`remove` is your repository responsibility. But in practice, you rarely need just `remove` (you may need `archive` for example) but this is other topic.

**Comment by fesor** [comment]
https://github.com/Arky9782/chat/blob/master/src/AppBundle/Services/Flush.php#L29

Persist should not be there. It's repository responsibility.

Persist - marks entity as managed. Flush - makes diff off all managed entities's state and generate SQL queries as single transaction. Please read about [unit of work](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html).
